waypoints:
  # 약국 대기 위치
  pharmacy_waiting:
    x: 0.669
    y: 1.257
    yaw: -3.127
  # 접수처 대기 위치
  reception_waiting:
    x: 0.078
    y: 0.965
    yaw: 1.543
  # 접수처 안내 목표 위치
  reception_goal:
    x: 0.240
    y: 1.049
    yaw: -1.619
  # 수납 창구 안내 목표 위치
  payment_goal:
    x: 0.390
    y: 1.077
    yaw: -1.597
  # 약국 안내 목표 위치
  pharmacy_goal:
    x: 0.699
    y: 1.035
    yaw: 0.023
  # 화장실 대기 위치
  restroom_waiting:
    x: 0.551
    y: 0.070
    yaw: 1.559
  # 화장실 안내 목표 위치
  restroom_goal:
    x: 0.573
    y: 0.233
    yaw: -1.491
  # 충전 위치 1
  charging_station_1:
    x: 0.283
    y: 0.016
    yaw: 1.568
  # 충전 위치 2
  charging_station_2:
    x: 0.025
    y: 0.016
    yaw: 0.014
  # 물리치료실 안내 목표 위치
  physical_therapy_goal:
    x: 1.415
    y: 0.393
    yaw: 0.091
  # 물리치료실 대기 위치
  physical_therapy_waiting:
    x: 1.470
    y: 0.209
    yaw: -2.969
  # 진료실 안내 목표 위치
  treatment_room_goal:
    x: 1.407
    y: -0.190
    yaw: 0.049
  # 진료실 대기 위치
  treatment_room_waiting:
    x: 1.494
    y: -0.366
    yaw: 3.106
  # X-ray실 안내 목표 위치
  xray_room_goal:
    x: 1.531
    y: -0.665
    yaw: 0.006
  # X-ray실 대기 위치
  xray_room_waiting:
    x: 1.534
    y: -0.927
    yaw: 3.140
  # CT실 대기 위치
  ct_room_waiting:
    x: 1.532
    y: -1.400
    yaw: -3.079
  # CT실 안내 목표 위치
  ct_room_goal:
    x: 1.479
    y: -1.541
    yaw: 0.023
  # 병동 안내 목표 위치
  ward_goal:
    x: 0.969
    y: -1.553
    yaw: -3.121
  # 병동 대기 위치
  ward_waiting:
    x: 0.864
    y: -1.446
    yaw: -0.017
  # MRI실 안내 목표 위치
  mri_room_goal:
    x: 0.839
    y: -1.001
    yaw: -3.126
  # MRI실 대기 위치
  mri_room_waiting:
    x: 0.834
    y: -0.806
    yaw: -0.013
  # 임상병리실 안내 목표 위치
  clinical_pathology_room_goal:
    x: 0.874
    y: -0.495
    yaw: -3.106
  # 임상병리실 대기 위치
  clinical_pathology_room_waiting:
    x: 0.788
    y: -0.402
    yaw: 0.062
