<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mingky_bringup</name>
  <version>0.0.0</version>
  <description>Launch and configuration package for the Mingky Care project.</description>
  <maintainer email="mingky-care@example.com">Mingky Care Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>mingky_guide_manager</exec_depend>
  <exec_depend>mingky_battery_guard</exec_depend>
  <exec_depend>mingky_event_gateway</exec_depend>
  <exec_depend>mingky_qr_reader</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>pinky_navigation</exec_depend>
  <exec_depend>pinky_bringup</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>ros2cli</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
